<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>name</key>
	<string>Zephyr</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.zephyr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.zephyr</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*\}</string>
			<key>name</key>
			<string>comment.block.documentation.zephyr</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.zephyr</string>
				</dict>
				<key>16</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.zephyr</string>
				</dict>
				<key>17</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.zephyr</string>
				</dict>
				<key>18</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.zephyr</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(values|t(ext|ime|itle|ype)|u(pper|(ser_(engagement|geo_select_region)))?|s(lice|ocial_share|ort|trip_tags|tr(r)?pos|ubstr)|keys|length|lower|map|md5|number|p(arse|ublic_share|ush)|r(andom|eplace|ound)|int(ersect)?|h(orizon_(interest|select|set_interest))?|a(ssert|bs|d(info)?|pi_(event|send|set_email|user))|bucket_list|cancel|contains|date|filter|first)(\()(.*?)(\))</string>
			<key>name</key>
			<string>meta.function.zephyr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|as|case|switch|foreach|lambda|\/if|\/foreach|break)\b</string>
			<key>name</key>
			<string>keyword.control.zephyr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.zephyr</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.zephyr</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.zephyr</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.zephyr</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.zephyr</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.zephyr</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.zephyr</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.zephyr</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\btrue\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.zephry2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bfalse\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.zephry2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnull\b</string>
			<key>name</key>
			<string>constant.language.boolean.null.zephry2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|%|\*|\-|\+|==|=|!=|!==|&amp;lt;=|&amp;gt;=|&amp;lt;|&amp;gt;|!|&gt;|&lt;|&lt;=|&gt;=|&amp;&amp;|&amp;amp;&amp;amp;|\?|:|\|\||\?\:</string>
			<key>name</key>
			<string>keyword.operator.zephyr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^( *)(?&lt;!\{)\w</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.zephyr</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.zephyr</string>
	<key>uuid</key>
	<string>44960b4f-2635-45d0-ac96-4271eb0c1326</string>
</dict>
</plist>
